### ISSUE TITLE
Problems with insert link (and others) - hidden overflow and labels too high

### ISSUE THREAD

**Issue by skyflyer** [froala/django-froala-editor#47]
A picture is worth a thousand words :)
<img width="835" alt="screen shot 2018-01-15 at 13 29 30" src="https://user-images.githubusercontent.com/415535/34942582-794fdb2a-f9f8-11e7-875b-55aaa4ccfed0.png">

1. You can see that the "Insert link" is hidden, because the editor does not have enough height. 
2. When you fix the overflow, the label is too high and thus the input is not visible.

The reason for the first issue is this CSS part (from forms.css):
```css
.form-row {
    overflow: hidden;
    padding: 10px;
    font-size: 13px;
    border-bottom: 1px solid #eee;
}
```

The reason for the second issue this CSS part (from forms.css):
```css
.aligned label:not(.vCheckboxLabel):after {
    content: '';
    display: inline-block;
    vertical-align: middle;
    height: 26px;
}
```

I temporarily fixed those issues with a custom CSS added to the admin:
```css
div.form-row {
    overflow: visible;
}

.aligned label:not(.vCheckboxLabel):after {
    content: none;
}
```
I can prepare a pull request with this fix if you'd like. I'm not sure what other (unwanted) effects could the `overflow:visible` have though.

I tested this with Django 1.11.4 and 1.11.9 and django-froala-editor 2.7.3.
